### PR TITLE
Support Building with Platformio

### PR DESCRIPTION
**Pull request by peteh**
Hi, 

I was looking into your project and am currently trying if it works for my blinds as well. 

As for me it's easier to build and develop with platformio (automatic library management, code completion, etc) I changed the project structure to support it as well as there were only minor changes needed. Platformio is way more advanced than the standard Arduino IDE and has a lot of features that make developing easier, e.g. web update right from the ide. 

It should still work with Arduino IDE as well except the source folder now is named src folder. 

Here is what I changed: 
 * add function declarations at the top of the file as platformio compiler needs them declared beforehand
 * outsource webpage to separate h file (for some reason platformio ran some macros on it and there was really strange behavior)
 * Fix some space issues (sprintf was potentially writing larger data than the buffer could hold)
 * Rename source to src folder to support compilation with platformio
 * add platformio.ini that contains the necessary dependencies and platform config for a wemos d1 mini

PS: unfortunately I cannot test compilation with Arduino IDE, as I currently have not set it up. 

If you accept the PR for platformio, I would integrate another feature afterwards (otherwise it would be hard to merge later). 
I plan to integrate auto discovery for home assistant. After setting up mqtt and the name of the blinds, e.g. "Office Blinds" the device would show up automatically in home assistant as soon as it connects to the mqtt server without further configuration in HA needed (Specification: https://www.home-assistant.io/docs/mqtt/discovery/). I've done this already for several other projects for myself. For example for doorman: https://github.com/peteh/doorman or my nuki bridge: https://github.com/peteh/nuki-esp32-bridge

### CODE REVIEW

**Comment by Electr1fying** [comment]
Hi Peter!

Did you by chance already implemented Auto Discovery in your xblinds fork? I've taken a look at xblinds regarding this before, but my programmings skills don't reach that far. I noticed Domoticz cannot do anything with the current MQTT messages because it expects these in JSON format.

Domoticz can also use HA Auto Discovery nowadays. It would be cool if this could be done!

Thanks in advance!

**Comment by peteh** [comment]
@Electr1fying I haven't but Auto Discovery would only work for Homeassistant. I don't know Domoticz.

**Comment by Electr1fying** [comment]
Hi Peter,

Thanks. Domoticz uses HA's implementation of Auto Discovery nowadays, so i reckon it should work perfectly fine.

**Comment by peteh** [comment]
Alright, I'm currently working with the code to get it to work with A4988 controllers as they provide more torque. As the original author does not respond for now, I think I'll put everything into my fork and start from there without merging back. 

I'll integrate auto discovery for sure but cannot commit to a date. Could be  a week, could be 3 months depending on my spare time.

**Comment by kp-bit** [comment]
Hi @peteh,

Thanks for your interest in the project. Moving to PlatformIO and Auto Discovery was on my radar for when my spare time would allow it. However, with 900+ downloads of the STL, I assume at least some would be interested in the code for the Arduino IDE so the v1.0 code would need to be preserved in that format.

I'll see if I can find the time soon to look over your modifications and compile+test it myself...

Not completely sure how these merges work.

**Comment by peteh** [comment]
As long as we keep the .ino file name of the main file the code should still work in arduino ide. 

If you accept the pull request it will be merged into your main branch.

**Pull request closed without merging**
